### ISSUE TITLE
standard output for xml results file

### ISSUE THREAD

**Issue by BogdanLivadariu** [schroepf/TestLab#1]
it would be great to have the xml file in standard xml report file such as JUnit

this would help ppl that have CI integrations to pull the xml results and pass them into a report build publisher, or something similar that would generate HTML files :)

I can see that the xml reports are similar with JUnit but is this how it was designed in the first place ?

**Comment by schroepf** [comment]
yes, this is why i created the android-xml-run-listener. I used it to generate JUnit xml report files which Jenkins CI could use to check the test results. So - as far as Jenkins is concerned - the output xml report should be in JUnit "standard"
