### ISSUE TITLE
The XML report is not generated in the target folder

### ISSUE THREAD

**Issue by alex-vungle** [schroepf/TestLab#14]
I followed your instructions, however I am not able to find the xml report in /storage/emulated/0/Android/data/, it reproduces on both real device and emulator

**Comment by schroepf** [comment]
Hi,

Which version of android-xml-run-listener are you using?

**Comment by alex-vungle** [comment]
I reviewed the code, actually the report is generated under /sdcard/Android/data/<test_package_name>

Please close this ticket.

**Comment by schroepf** [comment]
Ok, thanks for the feedback anyways... :)
